name: Check Links

on:
  schedule:
    - cron: "*/20 * * * *"  # Runs every 3 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run link checker
        run: python check_links.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add check_result.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update check result" && git push)
